# Generated by Django 3.0.5 on 2020-05-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginal', models.CharField(max_length=500)),
                ('polarity_original', models.FloatField()),
                ('subjectivity_original', models.FloatField()),
                ('polarity_google', models.FloatField()),
                ('subjectivity_google', models.FloatField()),
                ('target', models.CharField(max_length=500)),
                ('polarity_target', models.FloatField()),
                ('subjectivity_target', models.FloatField()),
            ],
        ),
    ]
